title: 'керес блог'
author: 'Айыына Керес'
keywords: ''
email: aintys@mail.ru
description: >-
  Привет! Меня зовут Айыына
path: ''
url: 'https://keresm.ru'

permalink: /:year-:month-:day-:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
- README.md

safe: true
lsi: false

include: [_pages]

paginate: 5
paginate_path: "/page:num/"

tag_page: '/tags/'

plugins: [rouge, jekyll-sitemap, jekyll-feed, jekyll-paginate]

future: true

timezone: Asia/Yakutsk
